@tool
extends "./import_synty.gd"


func _post_import(scene):
    config = SynyImportConfig.new()
    config.unusual_obj_roots = unusual_obj_roots
    config.material_dirs = material_dirs
    config.texture_map = texture_map

    import_pack(scene)

    return scene


const unusual_obj_roots = [
    "SM_Bld_Preset_Tower_01_Optimized",
    "SM_Wep_Ballista_Mounted_Rigged_01",
]


const material_dirs = {
    "DefaultMaterial": "",
    "PolygonFantasyKingdom_Mat_01_A": "",
    "PolygonFantasyKingdom_Mat_01_A_Emmisive": "",
    "PolygonFantasyKingdom_Mat_02_A": "",
    "PolygonFantasyKingdom_Mat_03_A": "",
    "PolygonFantasyKingdom_Mat_04_A": "",
    "PolygonFantasyKingdom_Mat_Castle_Roof": "",
    "PolygonFantasyKingdom_Mat_Castle_Wall_01": "",
    "PolygonFantasyKingdom_Mat_01_B": "Alts",
    "PolygonFantasyKingdom_Mat_01_C": "Alts",
    "PolygonFantasyKingdom_Mat_02_B": "Alts",
    "PolygonFantasyKingdom_Mat_02_C": "Alts",
    "PolygonFantasyKingdom_Mat_03_B": "Alts",
    "PolygonFantasyKingdom_Mat_03_C": "Alts",
    "PolygonFantasyKingdom_Mat_04_B": "Alts",
    "PolygonFantasyKingdom_Mat_04_C": "Alts",
    "PolygonFantasyKingdom_Mat_Castle_Wall_02": "Alts",
    "PolygonFantasyKingdom_Mat_Castle_Wall_03": "Alts",
    "PolygonFantasyKingdom_Mat_Castle_Wall_04": "Alts",
    "PolygonFantasyKingdom_Mat_Castle_Wall_05": "Alts",
    "PolygonFantasyKingdom_Mat_Flag_Symbol_01": "Flags",
    "PolygonFantasyKingdom_Mat_Flag_Symbol_02": "Flags",
    "PolygonFantasyKingdom_Mat_Flag_Symbol_03": "Flags",
    "PolygonFantasyKingdom_Mat_Flag_Symbol_04": "Flags",
    "Arrow": "FX_Materials",
    "Fire": "FX_Materials",
    "FX_CandleFlame": "FX_Materials",
    "FX_Default": "FX_Materials",
    "FX_Material_Soft_Glow": "FX_Materials",
    "Smoke_Dark": "FX_Materials",
    "Smoke_Mat_01": "FX_Materials",
    "Smoke_Mat_04": "FX_Materials",
    "Smoke_Mat_05": "FX_Materials",
    "Sun_Beams": "FX_Materials",
    "PolygonFantasyKingdom_Mat_Ground_Grass_01": "Ground_Mat",
    "PolygonFantasyKingdom_Mat_Ground_Grass_02": "Ground_Mat",
    "PolygonFantasyKingdom_Mat_Ground_Grass_03": "Ground_Mat",
    "PolygonFantasyKingdom_Mat_Ground_Mud_01": "Ground_Mat",
    "PolygonFantasyKingdom_Mat_Ground_Mud_02": "Ground_Mat",
    "PolygonFantasyKingdom_Mat_Ground_Mud_03": "Ground_Mat",
    "PolygonFantasyKingdom_Mat_Ground_Sand_01": "Ground_Mat",
    "PolygonFantasyKingdom_Mat_Ground_Sand_02": "Ground_Mat",
    "PolygonFantasyKingdom_Mat_Ground_Sand_03": "Ground_Mat",
    "BlankGrey": "Misc",
    "PolygonFantasyKingdom_Mat_Clouds": "Misc",
    "PolygonFantasyKingdom_Mat_Glass": "Misc",
    "PolygonFantasyKingdom_Mat_Glass_Cross": "Misc",
    "PolygonFantasyKingdom_Mat_Horse_01": "Misc",
    "PolygonFantasyKingdom_Mat_Horse_02": "Misc",
    "PolygonFantasyKingdom_Mat_Horse_03": "Misc",
    "PolygonFantasyKingdom_Mat_Paintings": "Misc",
    "PolygonFantasyKingdom_Mat_Water": "Misc",
    "PolygonFantasyKingdom_Mat_Water_Opaque": "Misc",
}


const texture_map = {
    "PolygonFantasyKingdom_Texture_01_A.png": "",
    "PolygonFantasyKingdom_Texture_02_A.png": "",
    "PolygonFantasyKingdom_Texture_03_A.png": "",
    "PolygonFantasyKingdom_Texture_04_A.png": "",
    "PolygonFantasyKingdom_Texture_01_B.png": "Alts",
    "PolygonFantasyKingdom_Texture_01_C.png": "Alts",
    "PolygonFantasyKingdom_Texture_02_B.png": "Alts",
    "PolygonFantasyKingdom_Texture_02_C.png": "Alts",
    "PolygonFantasyKingdom_Texture_03_B.png": "Alts",
    "PolygonFantasyKingdom_Texture_03_C.png": "Alts",
    "PolygonFantasyKingdom_Texture_04_B.png": "Alts",
    "PolygonFantasyKingdom_Texture_04_C.png": "Alts",
    "PolygonFantasyKingdon_Texture_Roof_Normal.png": "Castle",
    "PolygonFantasyKingdon_Texture_Roof_Slat_01.png": "Castle",
    "PolygonFantasyKingdon_Texture_Roof_Slat_02.png": "Castle",
    "PolygonFantasyKingdon_Texture_Roof_Slat_03.png": "Castle",
    "PolygonFantasyKingdon_Texture_Roof_Slat_04.png": "Castle",
    "PolygonFantasyKingdon_Texture_Roof_Tile_01.png": "Castle",
    "PolygonFantasyKingdon_Texture_Roof_Tile_02.png": "Castle",
    "PolygonFantasyKingdon_Texture_Roof_Tile_03.png": "Castle",
    "PolygonFantasyKingdon_Texture_Roof_Tile_04.png": "Castle",
    "PolygonFantasyKingdon_Texture_Roof_Tile_Normal.png": "Castle",
    "PolygonFantasyKingdon_Texture_Wall_Brick_01.png": "Castle",
    "PolygonFantasyKingdon_Texture_Wall_Brick_Normal.png": "Castle",
    "PolygonFantasyKingdon_Texture_Wall_Dungeon_01.png": "Castle",
    "PolygonFantasyKingdon_Texture_Wall_Dungeon_Normal.png": "Castle",
    "PolygonFantasyKingdon_Texture_Wall_Evil_01.png": "Castle",
    "PolygonFantasyKingdon_Texture_Wall_Evil_Normal.png": "Castle",
    "PolygonFantasyKingdon_Texture_Wall_Large_Brick_01.png": "Castle",
    "PolygonFantasyKingdon_Texture_Wall_Large_Brick_Normal.png": "Castle",
    "PolygonFantasyKingdon_Texture_Wall_Stucco_01.png": "Castle",
    "PolygonFantasyKingdon_Texture_Wall_Stucco_Normal.png": "Castle",
    "PolygonFantasyKingdom_Texture_Blue_Cross.png": "Flag_Symbols",
    "PolygonFantasyKingdom_Texture_Blue_Fleur.png": "Flag_Symbols",
    "PolygonFantasyKingdom_Texture_Blue_Head.png": "Flag_Symbols",
    "PolygonFantasyKingdom_Texture_Blue_Lion.png": "Flag_Symbols",
    "PolygonFantasyKingdom_Texture_Green_Cross.png": "Flag_Symbols",
    "PolygonFantasyKingdom_Texture_Green_Fleur.png": "Flag_Symbols",
    "PolygonFantasyKingdom_Texture_Green_Head.png": "Flag_Symbols",
    "PolygonFantasyKingdom_Texture_Green_Lion.png": "Flag_Symbols",
    "PolygonFantasyKingdom_Texture_Purple_Cross.png": "Flag_Symbols",
    "PolygonFantasyKingdom_Texture_Purple_Fleur.png": "Flag_Symbols",
    "PolygonFantasyKingdom_Texture_Purple_Head.png": "Flag_Symbols",
    "PolygonFantasyKingdom_Texture_Purple_Lion.png": "Flag_Symbols",
    "PolygonFantasyKingdom_Texture_Red_Cross.png": "Flag_Symbols",
    "PolygonFantasyKingdom_Texture_Red_Fleur.png": "Flag_Symbols",
    "PolygonFantasyKingdom_Texture_Red_Head.png": "Flag_Symbols",
    "PolygonFantasyKingdom_Texture_Red_Lion.png": "Flag_Symbols",
    "FX_Arrow.png": "FX_Textures",
    "FX_SunBeam_Particles.png": "FX_Textures",
    "Smoke_01.png": "FX_Textures",
    "PFK_Texture_Ground_Base_Normals.png": "Ground",
    "PFK_Texture_Ground_Grass_01_Dark.png": "Ground",
    "PFK_Texture_Ground_Grass_01.png": "Ground",
    "PFK_Texture_Ground_Grass_02_Normal.png": "Ground",
    "PFK_Texture_Ground_Grass_02.png": "Ground",
    "PFK_Texture_Ground_Grass_03_Normals.png": "Ground",
    "PFK_Texture_Ground_Grass_03.png": "Ground",
    "PFK_Texture_Ground_Mud_01.png": "Ground",
    "PFK_Texture_Ground_Mud_02.png": "Ground",
    "PFK_Texture_Ground_Mud_03.png": "Ground",
    "PFK_Texture_Ground_Sand_01.png": "Ground",
    "PFK_Texture_Ground_Sand_02_Normal.png": "Ground",
    "PFK_Texture_Ground_Sand_02.png": "Ground",
    "PFK_Texture_Ground_Sand_03_Normals.png": "Ground",
    "PFK_Texture_Ground_Sand_03.png": "Ground",
    "PolygonFantasyKingdom_Texture_Emmisive.png": "Misc",
    "PolygonFantasyKingdom_Texture_Glass_Crossed.png": "Misc",
    "PolygonFantasyKingdom_Texture_Horse_01.png": "Misc",
    "PolygonFantasyKingdom_Texture_Horse_02.png": "Misc",
    "PolygonFantasyKingdom_Texture_Horse_03.png": "Misc",
    "PolygonFantasyKingdom_Texture_Normal_01.png": "Misc",
    "PolygonFantasyKingdom_Texture_Normal_02.png": "Misc",
    "PolygonFantasyKingdom_Texture_Paintings_01.png": "Misc",
    "White.png": "Misc",
}
